### PR TITLE
new: [misp-object] File metadata objects organized by MIME type. 

### PR DESCRIPTION
**Pull request by VVX7**
A collection of objects containing MIME type specific metadata tags.  All tags have been extracted using Phil Harvey's ExifTool.  A script is included for rebuilding these objects from the test files.  

All object attributes are assumed to have a MISP attribute type of "text".  Some parsing of metadata tag values is performed to guess valid datetime and mime-type MISP attributes.

### CODE REVIEW

**Comment by Rafiot** [comment]
Thank you for your contribution.

I looked at the templates and there are a few blocking points, or at least things to think about:

1.The generic entries present for each files (keys starting with `File:`) are, or should be, in the existing file object template and should not be duplicated, unless there is a good reason not to.
2. The entries with a prefix EXIF should be a dedicated object
3. Other entries (with other prefixes) could be dedicated objects, if they make sense. 

The way to connect multiple objects together is to use relations.

**Comment by VVX7** [comment]
@Rafiot Thanks for the feedback.  I will move keys which fit in the current file object to the file object. This will include some of the `*-time` category keys such `FileInodeChangeDate`.

Before moving individual attributes to the most appropriate object, I want to first verify that this directory structure works for you. If it does not, can you suggest what you prefer to see?

What I've done here is use the existing ExifTool metadata categories (Author, Image, Time, etc) in generating lists of attributes. I think it's much simpler for the end user to find what they may be looking for rather than using the metadata location in file.  For reference ExifTool metadata groups [here](https://www.sno.phy.queensu.ca/~phil/exiftool/#groups).

The number of objects and attributes is still huge but if organized this way we can reduce confusion where several similar sounds attribute keys describe the same idea. I think it will also make working with these objects in the UI a little easier, though I've written a PyMISP tool to automate building and referencing objects and adding them to an event.

**Comment by Rafiot** [comment]
That's a lot of objects, in order to avoid polluting the existing namespace, it would probably be dood to have a dedicated object category "exif" instead of "file".

I'll look at the templates a bit more as soon as possible.

**Comment by VVX7** [comment]
@Rafiot I'm never going to find time to clean these up or maintain them. I think it's safe to close this issue.  If I need exif data for a file I can add it on a case by case basis :)

**Comment by Rafiot** [comment]
Sounds good, also, it was a crazy amount of templates I'm not sure how we could reasonably package it :)

**Pull request closed without merging**
