### PR TITLE
new misp-object: c2-list

### PR DESCRIPTION
**Pull request by bynt**
adds object for tracking c2 servers found in ransomware reports, blog posts or similar

### CODE REVIEW

**Comment by adulau** [comment]
Just to be sure, I understand the use-case for this new object.

What would be the different to use this one versus [ip-port](https://www.misp-project.org/objects.html#_ip_port) with a tag `adversary:infrastructure-type="c2"` from [adversary](https://www.misp-project.org/taxonomies.html#_adversary) taxonomy.

**Comment by bynt** [comment]
I guess that relations like `found in` or `retrieved from` would technically work, thanks for the pointer. We are basically looking for a convenient way to enter the data without too much friction, have it picked up automatically by our netflow test sytem and easily disregard, if the report turns out to be ~~rubbish~~ outdated, or promote to production, if the results are promising.

**Comment by adulau** [comment]
If you want to update the verbs/relationships let me know, I'll keep the PR update to be sure we are not missing anything else from the other objects.

**Comment by bynt** [comment]
Thx @adulau. I'm going to take part in the MISP training session on Monday and may come back with a fresh approach ;)

**Comment by adulau** [comment]
Don't hesitate to ping @mokaddem during the session on Monday about it.

**Comment by adulau** [comment]
Following a discussion with @mokaddem it seems you have a specific use-case to discard the complete list. I merged it. Thank you

**Pull request merged**
