### PR TITLE
added attribute link to file for external analysis ressource

### PR DESCRIPTION
**Pull request by c-goes**
attribute for a link with information about the file (external analysis)

### CODE REVIEW

**Comment by adulau** [comment]
A small question, would this be different than the [virustotal-report](https://github.com/MISP/misp-objects/tree/master/objects/virustotal-report)?

**Comment by c-goes** [comment]
It was supposed to be for links to a sandbox that has analyzed the sample.
Do you prefer a PR for another object similar to virustotal-report, maybe a sandbox-report object?

**Comment by adulau** [comment]
@c-goes this would be a great with the list of known sandboxes and a raw field to hold the report as-is. Thanks a lot!

**Comment by adulau** [comment]
I suppose we can close this PR?

**Comment by adulau** [comment]
Thank you!

**Pull request closed without merging**
