### PR TITLE
chg: [object] update narrative required object fields

### PR DESCRIPTION
**Pull request by VVX7**
update narrative required object fields

### CODE REVIEW

**Comment by adulau** [comment]
Just discover something in your PR(s). You are changing the UUID of the object template. You should keep the UUID fixed or do you have a specific reason to not do it?

**Comment by VVX7** [comment]
It was a mistake changing it in the first place.  Now I have a duplicate narrative object I need to remove.

**Comment by adulau** [comment]
Don't hesitate to make a new PR with the UUID you want to keep.

**Comment by VVX7** [comment]
It is probably better to keep the old one in case anyone else is already using the narrative object.  I've removed the duplicate with the new UUID on my instance.  Thanks!

**Comment by VVX7** [comment]
Hi @adulau this commit also fixes the UUID I changed by mistake back to the original UUID. Should I open a new PR to make this change instead?

**Comment by VVX7** [comment]
I've added two new objects to this PR. 
Social-media-group for things like facebook pages.  
scheduled-event defines an event in meatspace such as upcoming lockdown protests.

**Comment by adulau** [comment]
This is great. We will also use for the new modules in AIL for Telegram and other groups that we are discovering [new telegram module in AIL](https://github.com/CIRCL/AIL-framework/commit/927a8c96c5322a66408c17d62c8cb73ec6ddbb6c)

**Comment by VVX7** [comment]
@adulau I added `instant-message-group` a little while back for Telegram and others.  I realllllly to take another look at AIL when I get minute.

**Pull request merged**
