### PR TITLE
Added new objects

### PR DESCRIPTION
**Pull request by haxpak**
- new-object : Organization "Defines an organization"
- new-object : Device "Defines a device. Can be ralated to a forensic case"
- modified : person object "changed UI priority of the attributes"
- added : meta_category "organization" #162
- added : attachment attribute to annotation
- fixed typos and ran jq_all_things
- added requiredOneOf to device definition

### CODE REVIEW

**Comment by adulau** [comment]
This sounds very good to me. The device is indeed an useful one. Thank you very much.

**Comment by haxpak** [comment]
I am working on more, since i recently started using the platform.

**Comment by adulau** [comment]
Cool. Indeed for assigning glyphicons for objects, we would need to add this. Do you have something specific in mind? If you could open an issue with you would like and the use-case will have a look at it (some examples). We will have a look. Thanks a lot for the contributions.

**Comment by haxpak** [comment]
Well don't thank me.
I moved my team to the misp platform recently and fell in love.
I am using it everyday.
These objects were some things that I found were required by me and my
team, thus contributed them. More will keep coming up as we push more data
and deal with missing pieces.

I will open a issue regarding the glyphs
Thanks

**Pull request merged**
