### PR TITLE
chg: [cortex-taxonomy] sort attributes

### PR DESCRIPTION
**Pull request by mback2k**
Make sure the attributes are sorted like a Cortex taxonomy would normally be displayed/summarized:

`namespace:predicate="value"` with `level` as a meta information.

cc @tk-hendrik

### CODE REVIEW

**Comment by mback2k** [comment]
I don't see why the jq CI test fails, I just changed the values inside the existing JSON structure and not the structure itself.

**Comment by adulau** [comment]
Thanks a lot for your contribution.

You need to run jq afterwards. I suppose some of the fields were reordered by the ordering is done by jq to keep consistent diff across version of misp-objects.

**Comment by mback2k** [comment]
I just ran `jq_all_the_things.sh `for me locally and it completes successfully without any errors or additional changes to the file.

**Comment by adulau** [comment]
Thank you!

**Pull request merged**
