### PR TITLE
New attack-step object.

### PR DESCRIPTION
**Pull request by matthijsvp**
An object defining a singular attack-step. Especially useful for red/purple teaming, but can also be used for actual attacks.

Merged latest main branch.
Ran jq_all_the_things and validate_all.

### CODE REVIEW

**Comment by matthijsvp** [comment]
Test failed as I had a typo in disable_correlation. Has been fixed, but weird that it passed local validation.

**Comment by adulau** [comment]
Nice contribution! Thank you. Have you seen any relationship types missing when designing the object?

**Comment by matthijsvp** [comment]
I haven’t paid any attention to that honestly. Anything specific you are
thinking of?

**Comment by adulau** [comment]
I was thinking of all the actions that a threat-actor against various object described from the `attack-step`object. 

Maybe stuff like `gain-monetary-from`, `ransoms`, `search-for` ... everything which is not in https://github.com/MISP/misp-objects/blob/main/relationships/definition.json

**Comment by matthijsvp** [comment]
That’s a great idea! I was thinking how to describe different types of
attack steps in a structured way. The relations never crossed my mind. I’ll
work on them!

**Pull request merged**
