### PR TITLE
dnsdbflex object

### PR DESCRIPTION
**Pull request by aaronkaplan**

### CODE REVIEW

**Comment by aaronkaplan** [comment]
BTW... no idea why the check failed ( I don't have the sponge binary installed).

For me the jq-all-the-things.sh works:

```bash
% ./jq_all_the_things.sh | grep passive-dns
validating ./objects/passive-dns-dnsdbflex/definition.json
validating ./objects/passive-dns/definition.json
+ for dir in 'objects/*/definition.json'
+ cat objects/ail-leak/definition.json
+ jq -S -j .
+ sponge objects/ail-leak/definition.json
./jq_all_the_things.sh: line 22: sponge: command not found      # ignoring this since it does not relate to the PR.
```

**Comment by aaronkaplan** [comment]
@adulau or @iglocska could you please review? Thanks

**Comment by adulau** [comment]
Sure I'll have a look.

**Comment by adulau** [comment]
It was just a newline ;-) Thanks for the contribution. It's merged.

**Pull request merged**
